language: python
python:
  - 3.4
  - 3.5
  - 3.6
install:
  - python setup.py install
  - pip install httmock mypy pytest pytest-cov
  - pip install codecov
script:
  - pytest --cov
  - mypy google_measurement_protocol --ignore-missing-imports
after_success:
  - codecov
